---
batfish:
  type: batfish
  bf_host: localhost
  bf_nw_name: {{ network_name }}
  bf_ss_name: {{ snapshot_name }}
  bf_dir: ~/ool-mddo/playground/configs/{{ network_name }}/{{ snapshot_name }}
  state_dir: ~/ool-mddo/state_cross_checker/batfish_states/{{ network_name }}/{{ snapshot_name }}
  routes_file: ospf_route.json
  ospf_neighbors_file: ospf_neighbor.json
original:
  type: original
  state_dir: ~/ool-mddo/playground/configs/{{ network_name }}/{{ snapshot_name }}/status
  routes_dir: showroute
  routes_file: _show_route.txt
  ospf_neighbors_dir: showospfneigh
  ospf_neighbors_file: _show_ospf_neigh.txt
emulated:
  type: emulated
  state_dir: ~/ool-mddo/playground/configs/{{ network_name }}/{{ snapshot_name }}/status
  routes_dir: showroute
  routes_file: _show_route.txt
  ospf_neighbors_dir: showospfneigh
  ospf_neighbors_file: _show_ospf_neigh.txt
original_node_params:
  - name: RegionA-RT1
    type: juniper
    ospf: true
  - name: RegionA-RT2
    type: juniper
    ospf: false
  - name: RegionB-RT1
    type: arista
    ospf: true
  - name: RegionB-RT2
    type: arista
    ospf: true
  - name: RegionC-RT1
    type: cisco
    ospf: true
  - name: RegionC-RT2
    type: cisco
    ospf: false
